# Sistemas de ecuaciones lineales 
> Fundamentos matemáticos para la formulación y solución de sistemas de ecuaciones lineales 

- toc: true 
- badges: true
- comments: true
- categories: [Sistemas de ecuaciones lineales, Fundamentos, Teoría]

# **Definición de un sistema de ecuaciones lineales** 

<p align="justify">Antes abordar la solución computacional de un sistema de ecuaciones lineales debemos definir estos sistemas en cuestión, así bien, la forma general de un sistema de este tipo es:</p>

$$
\begin{gathered}
a_{1,1} x_1+a_{1,2} x_2+\ldots+a_{1, n} x_n=b_1 \\
a_{2,1} x_1+a_{2,2} x_2+\ldots+a_{2, n} x_n=b_2 \\
\vdots \\
a_{n, 1} x_1+a_{n, 2} x_2+\ldots+a_{n, n} x_n=b_n
\end{gathered}
$$

<p align="justify">Donde $x_{i}$ representa las variables desconocidas que estamos intentando hallar, $a_{i}$ son los coeficientes que acompañan a dichas variables y $b_{i}$ son los coeficientes a los cuales están igualadas nuestras ecuaciones. También cabe resaltar que para la solución de sistemas hemos de tener el mismo numero de ecuaciones que de variables desconocidas, esto para evitar sobre especificar el sistema. Con base en lo anterior, podemos escribir nuestro sistema de ecuaciones de forma matricial</p>
$$
\begin{gather*} 
\mathbf{Ax = b}
\end{gather*}
$$

<p align="justify">Donde $\mathbf{A}$ es la matriz de coeficientes</p>

$$
\mathbf{A}=\left[\begin{array}{cccc}
a_{1,1} & a_{1,2} & \cdots & a_{1, n} \\
a_{2,1} & a_{2,2} & \cdots & a_{2, n} \\
\vdots & \vdots & & \vdots \\
a_{n, 1} & a_{n, 2} & \cdots & a_{n, n}
\end{array}\right]
$$



<p align="justify">$\mathbf{x}$ es el vector de variables desconocidas</p>

$$
\mathbf{x}=\left[\begin{array}{c}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{array}\right]
$$

<p align="justify">Y $\mathbf{b}$ es el vector de constantes a las cuales están igualadas las ecuaciones</p>

$$
\mathbf{b}=\left[\begin{array}{c}
b_1 \\
b_2 \\
\vdots \\
b_n
\end{array}\right]
$$

# **Solución matricial de un sistema**

<p align="justify">Mediante el tratamiento algebraico de la $(eq.1)$ podemos despejar $\mathbf{x}$ </p>



$$
\begin{equation}
\mathbf{x = A^{-1}b}
\end{equation}
$$


<p align="justify">De forma que para hallar nuestro vector de variables desconociadas $\mathbf{x}$, simplemente debemos encontrar la matriz inversa de nuestra matriz $\mathbf{A}$ y multiplicarla por el vector $\mathbf{b}$ </p>

## Ejemplo de solución

### Solución paso a paso

<p align="justify">Suponga usted que se desea resolver el siguiente sistema de ecuaciones lineales:</p>


$$
\begin{aligned}
x_1+2 x_2-x_3 &=5 \\
-x_1+3 x_2+x_3 &=-2 \\
x_1-x_2+x_3 &=3
\end{aligned}
$$


Como primer paso debemos crear nuestra matriz $\mathbf{A}$ y nuestros vector $\mathbf{b}$ en base a los coheficientes de las ecuaciones:


In [ ]:
#importamos la libreria numpy
import numpy as np

"""
Vamos a crear una matriz uzando np.array 
ya que si no la usamos se nos  definiria como una lista y no una matriz
lo cual puede causar conflictos mas adelante en el codigo
"""
A=np.array([[1,2,-1],
   [-1,3,1],
   [1,-1,1]])

b=np.array([5,-2,3])


<p align="justify">Ahora según lo deducido en la $(eq.2)$ simplemente debemos hallar la matriz inversa de $\mathbf{A}$ y multiplicarla por $\mathbf{b}$</p>

In [ ]:
#Usando numpy halamos la iversa de A asi:
invA=np.linalg.inv(A)
#ahora multiplicamos invA por b para obtener x
x=invA@b
print(x)

[ 3.7  0.6 -0.1]


<p align="justify">De esta manera hemos solucionado el sistema, ahora bien, nótese que hemos descrito el proceso de solución paso a paso con el fin de que este sea más comprensible, sin embargo esto no nos impide realizar esta misma solución de una forma mas eficiente compactándola en una sola línea</p>

In [ ]:
x=(np.linalg.inv(A))@b
print(x)

[ 3.7  0.6 -0.1]


### Solución usando numpy

<p align="justify">Si bien es fundamental el conocer el paso a paso que nos lleva a la solución de un sistema, a nivel de aplicación los sistemas lineales en la mayoría de ocasiones no son el centro de estudio de un problema, sino mas bien una herramienta para la solución del mismo, es decir, puede que para encontrar la solución a un problema de aplicación, sea necesaria la resolución de uno o varios sistemas de ecuaciones lineales para obtener incógnitas valiosas que sean parte de ese problema.

<p align="justify">Es por esto que surge la necesitad de saber solucionar estos sistemas de manera rápida y precisa , ya que en la mayoría de los casos son simplemente parte de un problema mas grande, por esto se muestra a continuación como obtener estas soluciones de manera ágil mediante el uso del solver de la librería Numpy:



In [ ]:
import numpy as np
x=np.linalg.solve(A,b)
print(x)

[ 3.7  0.6 -0.1]


# Referencias
La teoría usada en este blog fue tomada de:

*   Dorfman, K. D. & Daoutidis, P. (2017). *Numerical Methods with Chemical Engineering Applications*. Cambridge University Press.


